apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-app-dev
  namespace: argocd

spec:
  project: banking-dev-project
  
  source:
    repoURL: https://github.com/yonatandas/Multi-Environment-Microservices.git
    targetRevision: main
    path: helm/environments/dev-env
    helm:
      valueFiles:
        - values.yaml
        - image-tags.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
  # Ignore HPA replica changes
  - group: apps
    kind: Deployment
    jsonPointers:
      - /spec/replicas
      - /status  # Ignore status changes
  
  # Ignore Secret data (updated by External Secrets Operator)
  - group: ''
    kind: Secret
    jsonPointers:
      - /data
      - /metadata/annotations
  
  # Ignore ConfigMap annotations (if needed)
  - group: ''
    kind: ConfigMap
    jsonPointers:
      - /metadata/annotations
      - /data/SPRING_PROFILES_ACTIVE
      - /data/JAVA_TOOL_OPTIONS
      - /data/OTEL_EXPORTER_OTLP_ENDPOINT
      - /data/OTEL_METRICS_EXPORTER
      - /data/OTEL_LOGS_EXPORTER
  
  # Ignore Service annotations (ALB controller adds these)
  - group: ''
    kind: Service
    jsonPointers:
      - /metadata/annotations
      - /status

