apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies-dev
  namespace: argocd
spec:
  project: banking-dev-project
  source:
    repoURL: https://github.com/yonatanDas/Multi-Environment-Microservices.git
    targetRevision: main
    path: kyverno/policies/cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

