apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-dev
  namespace: argocd
spec:
  project: banking-dev-project
  
  source:
    repoURL: https://github.com/YonatanDas/Banking-Microservices-Platform.git
    targetRevision: main
    path: monitoring/promtail
    helm:
      valueFiles:
        - values/dev.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true

