apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: banking-dev-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - 'https://github.com/yonatandas/Multi-Environment-Microservices.git'
    - '*'
  
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'external-secrets.io'
      kind: ClusterSecretStore
    - group: 'kyverno.io'
      kind: ClusterPolicy
    - group: 'kyverno.io'
      kind: Policy
    - group: 'monitoring.coreos.com'
      kind: PrometheusRule
  
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'autoscaling'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'external-secrets.io'
      kind: '*'
    - group: 'monitoring.coreos.com'
      kind: '*'
  
  roles:
    - name: dev-admin
      description: Dev environment administrator
      policies:
        - p, proj:banking-dev-project:dev-admin, applications, *, banking-dev-project/*, allow
        - p, proj:banking-dev-project:dev-admin, repositories, get, banking-dev-project/*, allow
      groups:
        - dev-team

