loki:
  auth_enabled: false
  
  # Explicit schema_config as required by Grafana Loki Helm chart validation
  # Per Grafana docs: schema_config is required for all Loki deployments
  # This minimal config works with filesystem storage for dev
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  storage:
    type: filesystem
  
  persistence:
    enabled: false

