loki:
  auth_enabled: false
  
  # Use test schema for dev environment (simpler, no persistence)
  useTestSchema: true
  
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  storage:
    type: s3
    bucketNames:
      loki: dev-loki-storage-063630846340
    s3:
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
      s3ForcePathStyle: false
      secretAccessKey: ""
      accessKeyId: ""

  serviceAccount:
    create: true
    name: loki
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::063630846340:role/dev-loki-s3-access-role

  persistence:
    enabled: false
    #size: 20Gi

