loki:
  auth_enabled: false
  
  # Schema config required for Loki deployments
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  storage:
    type: filesystem
  
  persistence:
    enabled: false

