opentelemetry-collector:
  mode: deployment  # Changed from daemonset
  
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.95.0"
  
  config: 
    exporters:
      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus:9090/api/v1/write
      loki:
        endpoint: http://loki-gateway:80/loki/api/v1/push
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      memory_limiter:
        limit_mib: 512
      resource:
        attributes:
          - key: deployment.environment
            value: dev
            action: upsert
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheusremotewrite]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [loki]
  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

