promtail:
  config:
    clients:
      - url: http://loki-gateway:80/loki/api/v1/push
    
    containerLogPaths:
      - /var/log/pods/*/*/*.log
    
    snippets:
      scrapeConfigs: |
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - docker: {}
          relabel_configs:
            # Filter running pods
            - action: keep
              source_labels:
                - __meta_kubernetes_pod_phase
              regex: Running
            # Construct log path
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_name
                - __meta_kubernetes_pod_uid
              separator: '_'
              target_label: __tmp_pod_path
            - action: replace
              regex: (.+)
              source_labels:
                - __tmp_pod_path
              target_label: __tmp_pod_path
              replacement: /var/log/pods/$1
            - action: replace
              regex: (.+)/(.+) 
              source_labels:
                - __tmp_pod_path
                - __meta_kubernetes_pod_container_name
              separator: /
              target_label: __path__
              replacement: $1/$2/*.log
            # Drop invalid paths
            - action: drop
              regex: ''
              source_labels:
                - __path__
            # Add labels
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
              target_label: app
              action: replace
            - source_labels: [__meta_kubernetes_pod_label_app]
              target_label: app
              action: replace
            # Remove temporary label
            - action: labeldrop
              regex: __tmp_pod_path

